---
Name: silverstripe-rejb
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    jobboardsiteconfig: BiffBangPow\SilverStripeREJB\Extensions\JobBoardSiteConfigExtension

Wilr\GoogleSitemaps\Control\GoogleSitemapController:
  extensions:
    sitemap: JobBoardSitemapExtension

SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.rejbcache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: "rejbcache"
