---
Name: silverstripe-rejb
---

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    jobboardsiteconfig: BiffBangPow\SilverStripeREJB\Extensions\JobBoardSiteConfigExtension

Wilr\GoogleSitemaps\Control\GoogleSitemapController:
  extensions:
    sitemap: JobBoardSitemapExtension
